[package]
name = "ha-store-rust"
version = "0.1.0"
authors = ["Mathieu St-Vincent <m@mats.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lru = "0.6.0"
